
env:
   global:
     - CONAN_REFERENCE: "Seastar/0.1"
     - CONAN_USERNAME: "cppchedy"
     - CONAN_LOGIN_USERNAME: "cppchedy"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/cppchedy/Seastar"

linux: &linux
   os: linux
   dist: xenial
   sudo: required
   language: python
   python: "3.6"
   addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-8
        - stow


install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
